### PR TITLE
Add new benchmarks for limited / unlimited nl2br

### PR DESCRIPTION
**Pull request by mlrv**
The purpose of this PR is to introduce benchmarks for the function modified in  [this PR on the main lila repo](https://github.com/ornicar/lila/pull/6408).

I'm not entirely sure I fully understand the philosophy behind this repo, I thought it was going to import individual functions from the main `lila` project and run benchmarks, but that doesn't seem to be the case. Am I doing things correctly?

### CODE REVIEW

**Comment by niklasf** [comment]
Benchmark results on my machine:
```
[info] HtmlEscape.testShortNewLinesLimited      avgt   15  1033,911 ± 16,237  ns/op
[info] HtmlEscape.testShortNewLinesUnlimited    avgt   15    86,947 ±  1,739  ns/op
```

**Comment by niklasf** [comment]
So ... what does this mean? Since a single page have can have many long texts, imo we should not give up an order of magnitude of performance so easily. I wonder if the regexes can be sufficiently optimized, for example by precompiling them, or if a more verbose handcoded solution is required.

**Comment by mlrv** [comment]
I'm not surprised to be honest... I'm definitely not a regex wizard so I don't know if there's a way to do everything in a single pass 🤔 

While it's true that giving up an order of magnitude in performance it's never nice, I wouldn't expect this to be a performance-critical part of the application, and the regex variation definitely makes the code a lot more readable compared to the previous version.

Your call I guess, I'm happy to refactor the solution to try and keep the same performance level if we think this drop is not acceptable.

**Comment by ddugovic** [comment]
Java documentation is detailed and accessible, although offhand I don't know whether Scala has syntactic sugar for pattern pre-compilation.

In Java to compile a pattern, use [Pattern#compile](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html)

**Comment by ornicar** [comment]
That's a very hot function, we need it to remain fast.

**Comment by mlrv** [comment]
> That's a very hot function, we need it to remain fast.

Sounds good @ornicar, I'll refactor the PR and introduce a new benchmark.

**Pull request merged**
